import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from "next/font/google"
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner"
// import dynamic from 'next/dynamic';
// const ClerkProviderNoSSR = dynamic(() => import('@clerk/nextjs').then(mod => mod.ClerkProvider), {
//   ssr: false,
// });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ['latin'] })

// export default function RootLayout({ children }) {
//   return (
//     // <div suppressHydrationWarning>

//     <ClerkProvider>
//       <html lang="en">
//         <body
//           className={outfit.className}
//         >
//           <Provider>
//             {children}
//           </Provider>
//           <Toaster />
//         </body>
//       </html>
//     </ClerkProvider>
//     // </div>

//   );
// }


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className} suppressHydrationWarning>
          <Provider>
            {children}
          </Provider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}


